{
 "title": "block_device",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_ip",
    "query": "select dev_ip from block_device"
   }
  ]
 },
 "panels": [
  {
   "title": "Page In Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_throughput as value,\n  \"page in throughput\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page Out Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_throughput as value,\n  \"page out throughput\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page In Latency (nanosecond)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_latency as value,\n  \"page in latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page Out Latency (nanosecond)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_latency as value,\n  \"page out latency\" as metric\nFROM block_device\nWHERE $__timeFilter(time) AND dev_ip = '$device_ip'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Data Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(time)), total_IO, remote_IO, pagein_throughput, pageout_throughput, pagein_latency, pageout_latency from block_device;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "content": "<a href=\"http://127.0.0.1:3000/d/000000003/infiniswap?refresh=10s&orgId=1\"> Back To Main Page </a>"
  }
 ]
}