{
 "title": "General Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of Devices",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  device_num as value,\n  \"number of device\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Number of Block Device",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  bd_num as value,\n  \"number of block device\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Page In Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_throughput as value,\n  \"page in throughput\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page Out Throughput (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_throughput as value,\n  \"page out throughput\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Number of Daemon",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  daemon_num as value,\n  \"number of daemon\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  RAM_free as value,\n  \"free\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  RAM_mapped as value,\n  \"used\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  RAM_allocated as value,\n  \"allocated but not used\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "IO Partition",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  (total_IO-remote_IO) as value,\n  \"local_IO\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  remote_IO as value,\n  \"remote_IO\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Page In Latency (nanosecond)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pagein_latency as value,\n  \"page in latency\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Page Out Latency (nanosecond)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pageout_latency as value,\n  \"page out latency\" as metric\nFROM general_info\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Block Device Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT dev_ip, total_IO, remote_IO, pagein_throughput, pageout_throughput, pagein_latency, pageout_latency FROM block_device WHERE $__timeFilter(time) GROUP BY dev_ip"
    }
   ]
  },
  {
   "title": "Daemon Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT dev_ip, RAM_free, RAM_filter_free, RAM_mapped, RAM_allocated FROM daemon WHERE $__timeFilter(time) GROUP BY dev_ip"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "content": " Device number: <input type=\"text\" id=\"num\"/><input type=\"button\" onclick=\"javascript:goto_blockdevice();\" value=\"submit\">\n    <script language=\"javascript\">\n    function goto_blockdevice(){\n        var num = document.getElementById(\"num\").value;\n        var href = \"http://128.110.96.95:3000/d/DxYJ2HSiz/block_device?orgId=1&from=now-5m&to=now&refresh=5s&panelId=2&var-device_id=\" + num;\n        //alert(href);\n        window.location.href = href;\n    }\n    </script>\n    <a href=\"http://128.110.96.95:3000/d/DxYJ2HSiz/block_device?orgId=1&from=now-5m&to=now&refresh=5s&panelId=2&var-device_id=1\"> link </a>\n    "
  }
 ]
}